import { Paper, Typography } from "@mui/material";
import { Container } from "@mui/system";
import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import { useResponsiveMaxWidth } from "../hooks/useResponsiveMaxWitdth";
import { useIsMobile } from "../utility/media_query_helper";

const Home: NextPage = () => {
  const isMobile = useIsMobile();
  const responsiveMaxWidth = useResponsiveMaxWidth();

  return (
    <>
      <Head>
        <title>QuillBook | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Paper sx={{ bgcolor: "primary.main", color: "primary.contrastText" }}>
          <Container
            sx={{
              maxWidth: responsiveMaxWidth,
              mx: isMobile ? undefined : "auto",
              width: "100%",
              px: isMobile ? "32px" : 0,
            }}
          >
            <Typography variant="h1">Welcome to QuillBook</Typography>
          </Container>
        </Paper>
      </Layout>
    </>
  );
};

export default Home;
