import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>QuillBook | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
        <h1 className={styles.title}>Welcome to QuillBook</h1>
      </Layout>
    </>
  );
};

export default Home;
